char_name = Charakter Name
main_class = Hauptklasse
main_class_level = Level der Hauptklasse
sub_class = Unterklasse
int = Intelligenz
str = Stärke
wis = Weisheit
cha = Charisma
con = Konstitution
dex = Geschicklichkeit
multiclass = Extra Klasse
multi_class_level = Extra Klasse Level
